init:
    $ circlewipe = ImageDissolve("wipes/circlewipe-cw.jpg", 1.0, 8)
    $ ccirclewipe = ImageDissolve("wipes/circlewipe-ccw.jpg", 1.0, 8)
    $ bites = ImageDissolve("wipes/bites.jpg", 1.0, 8)
    $ bowtie = ImageDissolve("wipes/bowtie.jpg", 1.0, 8)
    $ cmet = ImageDissolve("wipes/cmet.jpg", 1.0, 8)
    $ cwside = ImageDissolve("wipes/cw-side.jpg", 1.0, 8)
    $ cwtop = ImageDissolve("wipes/cw-top.jpg", 1.0, 8)
    $ dots = ImageDissolve("wipes/dots.jpg", 1.0, 8)
    $ edges = ImageDissolve("wipes/edges.jpg", 1.0, 8)
    $ flips = ImageDissolve("wipes/flips.jpg", 1.0, 8)
    $ fur = ImageDissolve("wipes/fur.jpg", 1.0, 8)
    $ goslow = ImageDissolve("wipes/goslow.jpg", 5.0, 8)
    $ letter = ImageDissolve("wipes/letter.jpg", 1.0, 8)
    $ maze = ImageDissolve("wipes/maze.jpg", 1.0, 8)
    $ radio = ImageDissolve("wipes/radio.jpg", 1.0, 8)
    $ snake = ImageDissolve("wipes/snake.jpg", 1.0, 8)
    $ snake2 = ImageDissolve("wipes/snake2.jpg", 1.0, 8)
    $ snakes = ImageDissolve("wipes/snakes.jpg", 1.0, 8)
    $ sunshine = ImageDissolve("wipes/sunshine.jpg", 1.0, 8)
    $ glasswool = ImageDissolve("wipes/glasswool.jpg", 1.0, 8)
    $ wet = ImageDissolve("wipes/wet.jpg", 1.0, 8)
    

    $ w1 = ImageDissolve("wipes/1.jpg", 1.0, 8)
    $ w2 = ImageDissolve("wipes/2.jpg", 1.0, 8)
    $ w3 = ImageDissolve("wipes/3.jpg", 1.0, 8)
    $ w4 = ImageDissolve("wipes/4.jpg", 1.0, 8)
    $ w5 = ImageDissolve("wipes/5.jpg", 1.0, 8)
    $ w6 = ImageDissolve("wipes/6.jpg", 1.0, 8)
    $ w7 = ImageDissolve("wipes/7.jpg", 1.0, 8)
    $ w8 = ImageDissolve("wipes/8.jpg", 1.0, 8)
    $ w9 = ImageDissolve("wipes/9.jpg", 1.0, 8)
    $ w10 = ImageDissolve("wipes/10.jpg", 1.0, 8)
    $ w11 = ImageDissolve("wipes/11.jpg", 1.0, 8)
    $ w12 = ImageDissolve("wipes/12.jpg", 1.0, 8)
    $ w13 = ImageDissolve("wipes/13.jpg", 1.0, 8)
    $ w14 = ImageDissolve("wipes/14.jpg", 1.0, 8)
    $ w15 = ImageDissolve("wipes/15.jpg", 1.0, 8)
    $ w16 = ImageDissolve("wipes/16.jpg", 1.0, 8)
    $ w17 = ImageDissolve("wipes/17.jpg", 1.0, 8)
    $ w18 = ImageDissolve("wipes/18.jpg", 1.0, 8)
    $ w19 = ImageDissolve("wipes/19.jpg", 1.0, 8)
    $ w20 = ImageDissolve("wipes/20.jpg", 1.0, 8)
    $ w21 = ImageDissolve("wipes/21.jpg", 1.0, 8)
    $ w22 = ImageDissolve("wipes/22.jpg", 1.0, 8)
    $ w23 = ImageDissolve("wipes/23.jpg", 1.0, 8)
    $ w24 = ImageDissolve("wipes/24.jpg", 1.0, 8)
    $ w25 = ImageDissolve("wipes/25.jpg", 1.0, 8)
    $ w26 = ImageDissolve("wipes/26.jpg", 1.0, 8)
    $ w27 = ImageDissolve("wipes/27.jpg", 1.0, 8)
    $ w28 = ImageDissolve("wipes/28.jpg", 1.0, 8)

    $ w29 = ImageDissolve("wipes/29.jpg", 1.0, 8)
    $ w30 = ImageDissolve("wipes/30.jpg", 1.0, 8)
    $ w31 = ImageDissolve("wipes/31.jpg", 1.0, 8)
    $ w32 = ImageDissolve("wipes/32.jpg", 1.0, 8)
    $ w33 = ImageDissolve("wipes/33.jpg", 1.0, 8)
 
    $ left_dissolve = ImageDissolve("wipes/left.png", .6, 256, mipmap =True, time_warp=_warper.ease)
    $ right_dissolve = ImageDissolve("wipes/right.png", .6, 256, mipmap =True, time_warp=_warper.ease)